- name: Setup server
  hosts: localhost
  become: true
  vars_files: ./server-vars.yaml
  roles:
    - role: gantsign.golang
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - tmux
          - make
          - gcc
          - git
          - gcc-c++
          - cmake
          - python3
          - python3-pip
          - python3-netaddr
          - clang
          - clang-devel
          - llvm
          - llvm-devel
          - llvm-static
          - kernel-devel
          - zlib-devel
          - elfutils-libelf-devel
          - ncurses-devel
          - libarchive
          - unzip
          - docker
        state: present

    - name: Install kubebuilder
      ansible.builtin.get_url:
        url: https://github.com/kubernetes-sigs/kubebuilder/releases/download/{{ kubebuilder_version }}/kubebuilder_linux_amd64
        dest: /usr/local/bin/kubebuilder
        mode: 751

    - name: Install operator-sdk
      ansible.builtin.get_url:
        url: https://github.com/operator-framework/operator-sdk/releases/download/{{ operator_sdk_version }}/operator-sdk_linux_amd64
        dest: /usr/local/bin/operator-sdk
        mode: 751

    - name: Install kubectl
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: 751

    - name: Install kind
      ansible.builtin.get_url:
        url: https://kind.sigs.k8s.io/dl/{{ kind_version }}/kind-linux-amd64
        dest: /usr/local/bin/kind
        mode: 751

    - name: Enable docker
      ansible.builtin.systemd_service:
        name: docker
        enabled: true
        state: started
        daemon_reload: true
